adding support for conditional attributes
godlikemouse/jquery.template.js pull request #1
Opened 2020-05-14 08:34 UTC by rajputvishal

say you have a dropdown and inside that dropdown few items are selected and some are not. So you will need "selected" attribute on some elements which are selected in that dropdown.

after this change one can have a template with a conditional attribute like this
<option data-item="{binding}" conditional-attribute-selected = "{binding.isSelected ? 'true' : null}" value="{binding.value}">binding.label </option>

if isSelected is falsy then the attribute will not be added.

2020-05-14 17:02 UTC, godlikemouse requested changes
I like the approach and the idea.  Perhaps we could shorten the name though.  How do you feel about changing "conditional-attribute-" to "if-"?  This way it would take the form of:

`<option data-item="{binding}" if-selected="{binding.isSelected ? 'true' : null}" value="{binding.value}">binding.label </option>`

I think the if statement should include the last dash as well:

`if(name.indexOf("conditional-attribute-") == 0)`

or

`if(name.indexOf("if-") == 0)`

2020-05-15 03:27 UTC, rajputvishal commented
updated the attribute name as suggested.

2020-05-16 00:13 UTC, godlikemouse approved these changes

2020-05-16 00:13 UTC, merged

2020-05-16 00:13 UTC, godlikemouse commented
Thank you for the contribution @rajputvishal :)